_BASE_: Base-D2SA-InstanceSegmentation.yaml
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.0001
  STEPS: () # neglect lr scheduler at first
  MAX_ITER: 100000 # equi 18 epochs, w.r.t bs 16, ~2000 training images in D2SA
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True
OUTPUT_DIR: ../data/train_outputs/m2f/d2sa/m2f_r50_bs4_100kiter_d2sa/
