_BASE_: maskformer2_R50_bs16_160k.yaml
MODEL:
  SEM_SEG_HEAD:
    # pixel decoder
    PIXEL_DECODER_NAME: "MSDeformAttnPixelDecoderv2"
OUTPUT_DIR: ../data/train_outputs/mask2former_pxdecoderv2_r50_bs16_160K/
#OUTPUT_DIR: ../data/train_outputs/test/
#SOLVER:
#  IMS_PER_BATCH: 1
#DATALOADER:
#  NUM_WORKERS: 0
